//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.HotelComment = new HashSet<HotelComment>();
            this.HotelImage = new HashSet<HotelImage>();
            this.Tour = new HashSet<Tour>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountOfStars { get; set; }
        public string CountryCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<HotelComment> HotelComment { get; set; }
        public virtual ICollection<HotelImage> HotelImage { get; set; }
        public virtual ICollection<Tour> Tour { get; set; }
    }
}
